INSERT INTO `resume-plus`.company_job (id, job) VALUES (1, '.NET 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (2, '2D 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (3, '3D 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (4, 'AS 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (5, 'ATL 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (6, 'BI 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (7, 'BI/BX 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (8, 'BTL 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (9, 'C,C++ 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (10, 'CAD·3D 설계자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (11, 'CBO,Chief Brand Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (12, 'CEO,Chief Executive Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (13, 'CFO,Chief Financial Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (14, 'CIO,Chief Information Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (15, 'CMO,Chief Marketing Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (16, 'COO,Chief Operation Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (17, 'CRM 전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (18, 'CS 매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (19, 'CS 어드바이저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (20, 'CSO,Chief Strategy Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (21, 'CTO,Chief Technology Officer');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (22, 'DBA');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (23, 'DevOps / 시스템 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (24, 'E-러닝');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (25, 'ERP전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (26, 'HR 컨설턴트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (27, 'HRBP');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (28, 'HRD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (29, 'I&C 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (47, 'iOS 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (30, 'IR');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (31, 'ISMS(정보보호체계)');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (32, 'MD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (33, 'Node.js 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (34, 'PD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (35, 'PHP 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (36, 'PM·PO');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (37, 'PR 전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (38, 'QA 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (39, 'QA,테스트 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (40, 'QC 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (41, 'RF 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (42, 'Sports 전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (43, 'UI,GUI 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (44, 'UX 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (45, 'VMD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (46, 'VR 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (48, '가구 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (49, '가맹점 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (50, '간병인');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (51, '간호 조무사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (52, '간호사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (53, '감정평가사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (54, '개발 매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (55, '건설 안전·품질·검사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (56, '건설 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (57, '건축가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (58, '건축시공·감리');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (59, '검안사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (60, '게임 그래픽 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (61, '게임 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (62, '게임 서버 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (63, '게임 아티스트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (64, '게임 클라이언트 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (65, '게임운영자(GM)');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (66, '견적 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (67, '경영 혁신가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (68, '경영지원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (69, '경찰관');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (70, '경호원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (71, '계리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (72, '고객성공매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (73, '고압설계 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (74, '공간 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (75, '공무원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (76, '공연 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (77, '공인회계사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (78, '공정 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (79, '공정 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (80, '관리인');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (81, '관세사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (82, '광고 기획자(AE)');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (83, '광고 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (84, '광산 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (85, '광산 안전 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (86, '교사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (87, '교수');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (88, '교재·교육기획');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (89, '교직원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (90, '구매담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (91, '구조공학 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (92, '그래픽 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (93, '그래픽스 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (94, '그로스 해커');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (95, '글로벌 마케팅');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (96, '금속 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (97, '금융공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (98, '급여담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (99, '기계 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (100, '기계·설비·설계');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (101, '기계제작 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (102, '기관사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (103, '기술 교육');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (104, '기술영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (105, '기술지원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (106, '기업영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (107, '내부영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (108, '내부통제 담당자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (109, '노무·노사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (110, '농업 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (111, '데이터 분석가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (112, '데이터 사이언티스트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (113, '데이터 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (114, '도면 담당자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (115, '도면 작성가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (116, '디젤 정비공');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (117, '디지털 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (118, '라이센스 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (119, '레스토랑 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (120, '로봇·자동화');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (121, '루비온레일즈 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (122, '리셉션');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (123, '리스크 관리 전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (124, '리크루터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (125, '리테일 MD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (126, '리포터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (127, '마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (128, '마케팅 디렉터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (129, '마케팅 전략 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (130, '마켓 리서처');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (131, '매장 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (132, '매장점원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (133, '머신러닝 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (134, '메뉴개발');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (135, '모바일 게임 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (136, '모바일 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (137, '모바일마케팅');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (138, '목수');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (139, '무역사무');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (140, '물류 분석가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (141, '물류담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (142, '물리 치료사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (143, '미디어 세일즈');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (144, '미생물학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (145, '미용사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (146, '바리스타');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (147, '바이어관리·상담·개발');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (148, '바텐더');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (149, '반도체·디스플레이');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (150, '방사선사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (151, '배관공');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (152, '배관설계 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (153, '배송담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (154, '법무 자문위원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (155, '법무관');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (156, '법무담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (157, '법무사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (158, '변리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (159, '변호사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (160, '병원 코디네이터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (161, '보건안전 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (162, '보세사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (163, '보안 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (164, '보안요원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (165, '보일러 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (166, '보험 에이전트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (167, '보호 관찰관');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (168, '부동산 자산 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (169, '부동산 중개사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (170, '브랜드 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (171, '블록체인 플랫폼 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (172, '비디오 제작');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (173, '비서');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (174, '비주얼머천다이저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (175, '빅데이터 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (176, '사내 강사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (177, '사내 심리상담가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (178, '사무보조');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (179, '사업개발·기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (180, '사업수주 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (181, '사진작가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (182, '사회복지사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (183, '산업 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (184, '산업 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (185, '상품기획자(BM)');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (186, '생명공학 연구원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (187, '생물의학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (188, '생산 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (189, '생산공학 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (190, '생산직 종사자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (191, '서버 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (192, '서비스 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (193, '서비스 운영');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (194, '석유공학 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (195, '선박 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (196, '선적,발송 사무원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (197, '설비 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (198, '섬유·의류·패션');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (199, '세라믹 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (200, '세무사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (201, '세미나/포럼 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (202, '세일즈 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (203, '소믈리에');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (204, '소방관');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (205, '소방안전 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (206, '소셜 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (207, '소프트웨어 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (208, '손해 사정관');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (209, '솔루션 컨설턴트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (210, '수사관');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (211, '수의 테크니션');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (212, '수의사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (213, '수출입사무');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (214, '승무원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (215, '시스템,네트워크 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (216, '시운전 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (217, '시추 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (218, '식품 MD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (219, '식품가공·개발');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (220, '실내건축');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (221, '아웃바운드 텔레마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (222, '아트 디렉터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (223, '안내원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (224, '안드로이드 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (225, '안전 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (226, '애견 미용사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (227, '애널리스트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (228, '애자일코치');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (229, '약사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (230, '약사 보조원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (231, '약학 분석 화학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (232, '언더라이터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (233, '언리얼 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (234, '에디터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (235, '여행 에이전트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (236, '연관공');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (237, '연구실 기사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (238, '연구원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (239, '연예,엔터테인먼트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (240, '영상 편집가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (241, '영상,모션 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (242, '영상,음성 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (243, '영양사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (244, '영업 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (245, '오피스 관리');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (246, '외국어교육');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (247, '외부영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (248, '외식업 종사자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (249, '요리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (250, '요양보호사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (251, '용접기사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (252, '운송 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (253, '운영 매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (254, '운전기사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (255, '운행 관리원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (256, '원산지관리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (257, '원자력·에너지');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (258, '웨어하우스');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (259, '웹 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (260, '웹 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (261, '웹 퍼블리셔');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (262, '유니티 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (263, '유전 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (264, '유전공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (265, '유지보수 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (266, '유치원·보육교사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (267, '유통 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (268, '음향 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (269, '응급구조사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (270, '의료기기 영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (271, '의무기록사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (272, '의사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (273, '이벤트 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (274, '인명 구조원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (275, '인바운드 텔레마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (276, '인사담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (277, '인스톨러');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (278, '인테리어 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (279, '인허가 담당 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (280, '일러스트레이터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (281, '임베디드 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (282, '임상병리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (283, '임상시험 간호사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (284, '임상시험 연구원');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (285, '임상심리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (286, '입·출고 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (287, '자격증·기술전문교육');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (288, '자금담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (289, '자동차 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (290, '자바 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (291, '자산관리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (292, '자산운용가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (293, '자원봉사자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (294, '자재관리·구매');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (295, '작가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (296, '작업 치료사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (297, '장비 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (298, '재료공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (299, '재무 담당자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (300, '재무 분석가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (301, '저널리스트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (302, '저수처리 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (303, '전기 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (304, '전기 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (305, '전기기계 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (306, '전략 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (307, '전문강사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (308, '전시 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (309, '전시 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (310, '전자 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (311, '전자계전 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (312, '정보 분석가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (313, '정보보호 담당자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (314, '정비공');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (315, '제과·제빵사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (316, '제약영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (317, '제어 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (318, '제조 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (319, '제조 테스트 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (320, '제품 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (321, '제품 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (322, '제휴');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (323, '조경 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (324, '조립 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (325, '조무사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (326, '조직관리');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (327, '조직문화');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (328, '주요고객사 담당자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (329, '준법감시인');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (330, '중장비 기술자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (331, '증례 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (332, '지게차 운전사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (333, '지리정보시스템');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (334, '지리학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (335, '지역 관리 매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (336, '지역 전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (337, '지점장');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (338, '지질공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (339, '직업군인');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (340, '청구 담당자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (341, '초·중·고 교사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (342, '총무');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (343, '출판 기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (344, '출판, 편집 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (345, '측량·계측');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (346, '치과 위생사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (347, '치과의사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (348, '카운셀러');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (349, '카피라이터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (350, '캐디');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (351, '캐릭터 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (352, '컨설턴트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (353, '콘텐츠 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (354, '콘텐츠 크리에이터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (355, '큐레이터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (356, '크로스플랫폼 앱 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (357, '키워드광고');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (358, '터빈공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (359, '토목기사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (360, '통·번역');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (361, '투자·증권');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (362, '투자은행가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (363, '트레이더');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (364, '특허담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (365, '파이썬 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (366, '패브릭 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (367, '패션 MD');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (368, '패션 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (369, '패키지 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (370, '퍼포먼스 마케터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (371, '페인터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (372, '평가·보상');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (373, '푸드스타일리스트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (374, '품질 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (375, '프로덕트 매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (376, '프로젝트 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (377, '프론트엔드 개발자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (378, '플라스틱 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (379, '플랜트 관리자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (380, '플랜트 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (381, '플로리스트');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (382, '피부관리사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (383, '하드웨어 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (384, '학원강사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (385, '한의사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (386, '항공 운송');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (387, '항공우주 공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (388, '항해사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (389, '해양공학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (390, '해외 사업개발·기획자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (391, '해외영업');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (392, '해운·해양 운송');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (393, '헤드헌터');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (394, '헤어 디자이너');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (395, '헬스케어매니저');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (396, '현장 소장');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (397, '호흡장애 치료사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (398, '화물트럭 운전기사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (399, '화학공학 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (400, '화학자');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (401, '환경 안전기사');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (402, '환경 엔지니어');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (403, '환경 전문가');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (404, '회계·경리');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (405, '회계담당');
INSERT INTO `resume-plus`.company_job (id, job) VALUES (406, '회전기계 엔지니어');
